version: "3"
services:
  image-converter:
    build: 
      context: .
      dockerfile: Dockerfile
    image: python-rembg-image-converter:latest
    container_name: image-converter
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true